const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto"),url=require("url");
const PORT=process.env.PORT||3000, ADMIN_USER=process.env.ADMIN_USER||"admin", ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"change-this-password";
const ROOT=__dirname, DATA=path.join(ROOT,"data"), PF=path.join(DATA,"products.json"), OF=path.join(DATA,"orders.json");
fs.mkdirSync(DATA,{recursive:true});
function read(f,d){try{return JSON.parse(fs.readFileSync(f,"utf8"))}catch{return d}} function write(f,d){fs.writeFileSync(f,JSON.stringify(d,null,2))}
if(!fs.existsSync(PF))write(PF,DEFAULT_PRODUCTS); if(!fs.existsSync(OF))write(OF,[]);
function out(res,status,body,type="application/json"){res.writeHead(status,{"Content-Type":type,"Cache-Control":"no-store"});res.end(type==="application/json"?JSON.stringify(body):body)}
function body(req){return new Promise((ok,no)=>{let s="";req.on("data",c=>s+=c);req.on("end",()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(e)}});req.on("error",no)})}
function admin(req){let h=req.headers.authorization||"";if(!h.startsWith("Basic "))return false;let x=Buffer.from(h.slice(6),"base64").toString(),i=x.indexOf(":");return i>=0&&x.slice(0,i)===ADMIN_USER&&x.slice(i+1)===ADMIN_PASSWORD}
const DEFAULT_PRODUCTS=[{"id":"cement-jagdamba-ppc","category":"Cement","brand":"Jagdamba","name":"Jagdamba PPC Cement","size":"50 kg","unit":"bag","price":500,"stock":true,"image":"assets/jagdamba-ppc.png"},{"id":"cement-ultra-opc","category":"Cement","brand":"Ultra","name":"Ultra OPC Cement","size":"50 kg","unit":"bag","price":600,"stock":true,"image":"assets/ultra-opc.png"},{"id":"tmt-jagdamba","category":"TMT Steel","brand":"Jagdamba","name":"Jagdamba TMT Steel","size":"Multiple mm sizes","unit":"kg","price":100,"stock":true,"image":"assets/jagdamba-tmt.png"},{"id":"paint-royale","category":"Asian Paints","brand":"Asian Paints","name":"Royale Luxury Emulsion","size":"Pack size varies","unit":"pack","price":10000,"stock":true,"image":"assets/asian-paints-royale.png"},{"id":"paint-apex","category":"Asian Paints","brand":"Asian Paints","name":"Apex Dust Proof","size":"Pack size varies","unit":"pack","price":20000,"stock":true,"image":"assets/asian-paints-apex.png"},{"id":"wall-putty","category":"Wall Putty","brand":"Om Sai","name":"Wall Putty","size":"Pack size varies","unit":"bag","price":1200,"stock":true,"image":"assets/jagdamba-ppc.png"},{"id":"safecrete","category":"Construction Chemicals","brand":"Safecrete","name":"Safecrete Construction Chemical","size":"Contact shop for pack size","unit":"pack","price":null,"stock":true,"image":"assets/ultra-opc.png"},{"id":"belcha","category":"Equipment","brand":"Hardware","name":"Belcha / Shovel","size":"Standard","unit":"piece","price":300,"stock":true,"image":"assets/belcha.png"},{"id":"kathara","category":"Equipment","brand":"Hardware","name":"Kathara","size":"Standard","unit":"piece","price":300,"stock":true,"image":"assets/belcha.png"},{"id":"kudal","category":"Equipment","brand":"Hardware","name":"Kudal","size":"Standard","unit":"piece","price":300,"stock":true,"image":"assets/belcha.png"},{"id":"binding-wire","category":"Binding Wire","brand":"Jagdamba","name":"Jagdamba Binding Wire","size":"Standard","unit":"kg","price":null,"stock":true,"image":"assets/jagdamba-tmt.png"}];
http.createServer(async(req,res)=>{
 try{
  let p=url.parse(req.url).pathname;
  if(req.method==="GET"&&p==="/api/products")return out(res,200,read(PF,DEFAULT_PRODUCTS));
  if(req.method==="GET"&&p==="/api/orders"){if(!admin(req))return out(res,401,{error:"Unauthorized"});return out(res,200,read(OF,[]).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)))}
  if(req.method==="POST"&&p==="/api/orders"){let b=await body(req);if(!b.name||!b.phone||!b.address||!b.items?.length)return out(res,400,{error:"Missing customer/order details"});let ps=read(PF,DEFAULT_PRODUCTS);let items=b.items.map(i=>{let x=ps.find(q=>q.id===i.id);if(!x)throw Error("Unknown product");return{id:x.id,name:x.name,unit:x.unit,price:x.price,quantity:Math.max(1,Number(i.quantity)||1)}});let total=items.reduce((s,i)=>s+(typeof i.price==="number"?i.price*i.quantity:0),0);let o={id:"OSI-"+crypto.randomBytes(3).toString("hex").toUpperCase(),createdAt:new Date().toISOString(),customer:{name:String(b.name).trim(),phone:String(b.phone).trim(),address:String(b.address).trim()},payment:b.payment||"Cash on Delivery",items,total,status:"NEW"};let os=read(OF,[]);os.push(o);write(OF,os);return out(res,201,o)}
  if(req.method==="PATCH"&&p.startsWith("/api/orders/")){if(!admin(req))return out(res,401,{error:"Unauthorized"});let id=decodeURIComponent(p.split("/").pop()),b=await body(req),allowed=["NEW","CONFIRMED","PREPARING","OUT FOR DELIVERY","DELIVERED","CANCELLED"],os=read(OF,[]),o=os.find(x=>x.id===id);if(!o)return out(res,404,{error:"Not found"});if(!allowed.includes(b.status))return out(res,400,{error:"Invalid status"});o.status=b.status;o.updatedAt=new Date().toISOString();write(OF,os);return out(res,200,o)}
  if(req.method==="PUT"&&p.startsWith("/api/products/")){if(!admin(req))return out(res,401,{error:"Unauthorized"});let id=decodeURIComponent(p.split("/").pop()),b=await body(req),ps=read(PF,DEFAULT_PRODUCTS),x=ps.find(q=>q.id===id);if(!x)return out(res,404,{error:"Not found"});["name","category","brand","size","unit","image","price","stock"].forEach(k=>{if(b[k]!==undefined)x[k]=b[k]});write(PF,ps);return out(res,200,x)}
  let file=path.join(ROOT,p==="/"?"index.html":p==="/admin"?"/admin.html":p);if(!file.startsWith(ROOT)||!fs.existsSync(file))return out(res,404,"Not found","text/plain");
  let ext=path.extname(file),types={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg"};return out(res,200,fs.readFileSync(file),types[ext]||"application/octet-stream")
 }catch(e){console.error(e);out(res,500,{error:e.message})}
}).listen(PORT,()=>console.log("Om Sai International: http://localhost:"+PORT));